

static const int M_f0P0 = (0+1) * (1);
static const int M_f0P1 = (0+1) * (1);
static const int M_f1P0 = (0+1) * (1);
static const int M_f1P1 = (0+1) * (1);
static const int M_f2P0 = (0+1) * (1);
static const int M_f2P1 = (0+1) * (1);
static const int M_f3P0 = (0+1) * (1);
static const int M_f3P1 = (0+1) * (1);
static const int M_f4P0 = (0+1) * (1);
static const int M_f4P1 = (0+1) * (1);
static const int M_f5P0 = (0+1) * (1);
static const int M_f5P1 = (0+1) * (1);
static const int M_X0WC = (9853+0) * (1);
static const int M_X1WC = (9492+0) * (1);
static const int M_X2WC = (14352+0) * (1);
static const int M_X3WC = (16230+0) * (1);
static const int M_X4WC = (8192+0) * (1);
static const int M_X5WC = (8448+0) * (1);
static const int M_X0PC = (8384+0) * (1);
static const int M_X1PC = (8532+0) * (1);
static const int M_X2PC = (8394+0) * (1);
static const int M_X3PC = (8192+0) * (1);
static const int M_X4PC = (8782+0) * (1);
static const int M_X5PC = (8256+0) * (1);
static const int M_X0W0 = (161+0) * (64);
static const int M_X1W0 = (193+0) * (64);
static const int M_X2W0 = (216+0) * (64);
static const int M_X3W0 = (211+0) * (64);
static const int M_X4W0 = (393+0) * (64);
static const int M_X5W0 = (477+0) * (64);
static const int M_X0wr = (11842+0) * (1);
static const int M_X1wr = (8102+0) * (1);
static const int M_X2wr = (12320+0) * (1);
static const int M_X3wr = (6592+0) * (1);
static const int M_X4wr = (2+0) * (1);
static const int M_X5wr = (713+0) * (1);
static const int M_f0mw = (0+1) * (1);
static const int M_f1mw = (2049+1) * (1);
static const int M_f2mw = (392+1) * (1);
static const int M_f3mw = (0+1) * (1);
static const int M_f4mw = (2002+1) * (1);
static const int M_f5mw = (1918+1) * (1);
static const int M_f0wr0 = (15860+1) * (1);
static const int M_f1wr0 = (30422+1) * (1);
static const int M_f2wr0 = (32703+1) * (1);
static const int M_f3wr0 = (25468+1) * (1);
static const int M_f4wr0 = (32382+1) * (1);
static const int M_f5wr0 = (32513+1) * (1);
static const int M_f0wr1 = (37+1) * (1);
static const int M_f1wr1 = (4171+1) * (1);
static const int M_f2wr1 = (65+1) * (1);
static const int M_f3wr1 = (14257+1) * (1);
static const int M_f4wr1 = (697+1) * (1);
static const int M_f5wr1 = (309+1) * (1);
static const int M_f0C = (8384+0) * (1);
static const int M_f1C = (23045+0) * (1);
static const int M_f2C = (10904+0) * (1);
static const int M_f3C = (32754+0) * (1);
static const int M_f4C = (32664+0) * (1);
static const int M_f5C = (16384+0) * (1);



struct M_T {

  
  void M_Init( void ) {
  
  }
  void M_Quit( void ) {
  }
};
